### ISSUE TITLE
Use Termion?

### ISSUE THREAD

**Issue by ticki** [viseztrance/flow#1]
[Termion](https://docs.rs/termion/1.1.3/termion/) is pure Rust and provides all of ncurses' features. It shouldn't be that hard to replace.

**Comment by viseztrance** [comment]
I'm all for a thread safe ui with a saner api.

So I would like to use it, but I've looked over termion before choosing ncurses and it felt lacking feature wise. It didn't appear to handle windows, subwindows, panels or menus.

**Comment by ticki** [comment]
> It didn't appear to handle windows, subwindows, panels or menus.

You're right, and neither of these are a goal. Maybe check out Cursive?

**Comment by viseztrance** [comment]
It looked very promising and gave it a shot early on. There's a nice "log" viewer in its the examples folder that had me compelled. 

But in practice it just didn't work for my use case. Removing unwanted shadows, moving the menu down proved to be a lot of work, while trivial in plain ncurses. There's also the fact that it doesn't support newpad which I found essential for having smooth scrolling of large content.

**Comment by gyscos** [comment]
Thanks for your input!
Adding a shadow on every layer can indeed be bothersome sometimes, and I plan on making it easy to add "shadowless" layers.

About the scrolling performance, I'd be interested in an example where this is an issue, to design a better solution. Most of the time, bad performance is caused by re-layouting the text, so I'm sure we can avoid that without direct newpad support.
